version: "3.8"

services:
  youtube-playlist-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-processor
    ports:
      - "8080:8080" # Not necessary for GUI but can be removed/adjusted if needed
    volumes:
      - ./output:/app/output # Bind volume for saving outputs to host
    environment:
      GEMINI_API_KEY: "YOUR_GEMINI_API_KEY_HERE" # Set your API Key in .env or replace this line
    stdin_open: true
    tty: true
